### PR TITLE
ocyths#0758-howlsocial-howldocs

### PR DESCRIPTION
**Pull request by 0htjit**

### CODE REVIEW

**Comment by the-frey** [comment]
Hi, thanks for the PR. Could you fix the build errors please? 

The files are markdown, so the errors are probably from the use of HTML - suggest that you format it all as markdown & then it should build okay 🙏

**Comment by 0htjit** [comment]
> Hi, thanks for the PR. Could you fix the build errors please?
> 
> The files are markdown, so the errors are probably from the use of HTML - suggest that you format it all as markdown & then it should build okay 🙏

Already edit my post, hope it okay right now..

**Comment by the-frey** [comment]
Those images need to be inside the repository, not external links. They should be placed in the `/static/img` folder.

An image looks like this `image description` in markdown.

For ref: https://docusaurus.io/docs/static-assets#in-markdown

Also the build is still failing.

**Comment by cryptomanyaq** [comment]
## CLAIM $HOWL AIRDROP

The first thing you have to do is login to your KEPLR wallet
Than you can go to: https://testnet-claim.howl.social/, connect with your KEPLR wallet
<p align="center">
  
  
</p>

You'll requested to add "Uni wallet-3" chain, wich mean is JUNO Testnet, and than Approve.
<p align="center">
  
</p>

<p align="center">
  
</p>

After that you should be able to see <your-address> **can claim X HOWL** after connecting your wallet. If you are not eligible, you will see <your-address> **was not eligible** for the Howl airdrop.
<p align="center">
  
</p>

That's it, enjoy your HOWL airdrop

**Comment by 0htjit** [comment]
> Those images need to be inside the repository, not external links. They should be placed in the `/static/img` folder.
> 
> An image looks like this `image description` in markdown.
> 
> For ref: https://docusaurus.io/docs/static-assets#in-markdown
> 
> Also the build is still failing.

Already change the format of image, but image now showing. You can see the article. But i dont know if still not working, im not a coder, i just trying create tutorial with format in MEDIUM.

**Comment by the-frey** [comment]
Thanks for the submission. I will fix it as it will be quicker. 

This claims documentation challenges A, B, C, D, E

**Comment by 0htjit** [comment]
> Thanks for the submission. I will fix it as it will be quicker.
> 
> This claims documentation challenges A, B, C, D, E

so you accepted my submission sir for additional HOWL? i will share it to my community.. i think it will help them to try HOWL Alpha test

**Comment by the-frey** [comment]
@0htjit you are ocyths#0758 on Discord? 
Could you confirm what your address was that was in the airdrop?

**Comment by 0htjit** [comment]
> @0htjit you are ocyths#0758 on Discord? Could you confirm what your address was that was in the airdrop?

Yes sir, my discord is: ocyths#0758
And this is my address: juno1fsafyk2esceml9kg29zek6tfmwe2ru4dw4narm

**Pull request merged**
