### PR TITLE
Introduction to Howl Social

### PR DESCRIPTION
**Pull request by DonCryptonium**
Video introduction by Don Cryptonium to Howl Social Beta.
Include:
1. Claim Junox (testnet token)
2. Claim Airdrop
3. Buy Densh Name
4. Use Howl Social

### CODE REVIEW

**Comment by DonCryptonium** [comment]
Better give me that precious $howl!

**Comment by the-frey** [comment]
FYI - Stake and Post video is set to private. 

These are really good though, we will definitely award a discretionary bounty for this work. Thanks!

**Comment by the-frey** [comment]
Oh, and what's the video address for `How to Request JunoX testnet token:`?

**Comment by DonCryptonium** [comment]
Sorry for delay It wasn't finished. 
It is done now and includes all vids! Gonna open pull request if you'd like to include that.

**Comment by the-frey** [comment]
@DonCryptonium Aha, didn't realise that. If you want to do a PR, then maybe fork current `main` and do a fresh PR as I've tidied up the structure, fixed links etc and there have been a bunch of other changes 👍

**Pull request merged**
